meta_product_name: "Knock-Knock"
meta_title: "Knock-Knock - Discover digital nomad workers around you"
meta_description: "Discover digital nomad workers around you. You can chat with each others, get help from expertes of your domain. Publish posts to the community around you."
meta_image: "meta-image.png" # should exist in `app/assets/images/`
